### ISSUE TITLE
error while building SampleEnclave program

### ISSUE THREAD

**Issue by soso19932603** [01org/linux-sgx#116] opened 2017-06-14 09:59 UTC
Hello,
when i am trying to build SampleEnclave program, using make command i get this error:
 
make: *** No rule to make target '/opt/intel/sgxsdk/bin/x64/sgx_edger8r', needed by 'App/Enclave_u.c'.

What does it mean?

**Comment by soso19932603** [comment] 2017-06-14 12:24
I have found solution, when installing sgx sdk with the following command 
 sudo ./sgx_linux_x64_sdk_${version}.bin . It suggest two choice : 
  1- install sdk in current directory.  or   
  2- Another one. 
So i have chosen the second suggestion : (/opt/intel).

**Comment by johnvenn** [comment] 2017-06-14 12:34
notice there was a message on the end of sgxsdk installation -- run this command "source your_selected_sdk_installation_path/environment"

**Comment by lzha101** [comment] 2017-06-15 03:20
Just as @johnvenn mentioned, you need to source the environment before you build the SampleEnclave.

**Comment by soso19932603** [comment] 2017-06-21 11:39
Yes it also works, thanks for your responses

**Comment by lzha101** [comment] 2017-06-27 07:11
If no other errors, can we close this issue? @soso19932603

**Comment by soso19932603** [comment] 2017-06-27 08:28
No other errors, we can close it, thanks !

**Closed** 2017-06-27 08:47 UTC

**Comment by BSDinis** [comment] 2018-06-19 16:18
I sourced the environment and it still gives me this exact error message

**Comment by simplespy** [comment] 2018-07-12 23:48
I have the same problem even after setting the source

**Comment by andyzyb** [comment] 2018-07-16 00:51
It may be caused by sample code Makefile.  Is that sample code you are using the latest one from github?

**Comment by Jiax-cn** [comment] 2021-12-14 11:41
> 

Thank u!  I reinstall the SDK to `/opt/intel`, problem solved.
