### ISSUE TITLE
sgx-gdb yields python errors on every ocall

### ISSUE THREAD

**Issue by mikehearn** [01org/linux-sgx#26] opened 2016-09-30 09:14 UTC
When running my enclave in sim mode with the sgx-gdb tool I get errors like this:

Python Exception <class 'TypeError'> %x format: an integer is required, not gdb.Value: 

Breakpoint -8, notify_gdb_to_update (base=0x7fffed991000, tcs=0x7ffff3fcb000, of=140737488344768) at /home/mike/linux-sgx/psw/urts/linux/debugger_support.cpp:116

This happens every time my enclave does an ocall, it seems. Looks like an easily fixed error?

**Comment by andyzyb** [comment] 2016-09-30 14:49
Thanks for reporting the issue, but team is out for a week due to public holiday. Will try to reproduce the issue when back.

**Comment by mikehearn** [comment] 2016-09-30 15:11
No worries, enjoy your holiday!

**Comment by bl4ck5un** [comment] 2016-10-05 13:38
On a similar note, when debugged in sgx-gdb, the program receives SIGGEGV:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5009f6b in enter_enclave ()
```

Can be reproduced using the SampleEnclave shipping with the SDK.

**Comment by zhaohuidu** [comment] 2016-10-08 03:07
What is your Ubuntu version and gdb version?
According to feedback from team, there're bug in latest gdb so that if you upgrade your Ubuntu into some newer version such as 16.04, you will encounter such kind of problem.
And it is difficult to fix since the version of python is used by the gdb internally

**Comment by mikehearn** [comment] 2016-10-08 14:28
Yes, I'm on Xenial. OK, so if I downgrade gdb it might work?

**Comment by zhaohuidu** [comment] 2016-10-08 23:38
We have not tried it. You could have a try by yourself.

**Comment by bl4ck5un** [comment] 2016-10-10 15:46
@zhaohuidu What is the gdb version you think would work best?

**Comment by lifeasageek** [comment] 2016-10-20 14:25
I've fixed this issue on my branch. Check if this works - https://github.com/lifeasageek/linux-sgx/commit/f369b5f186c597c9d134e4d6ea1c4bd17485a21e

**Comment by andyzyb** [comment] 2016-10-21 04:50
We already have a fix locally, and push it soon.

**Comment by andyzyb** [comment] 2016-10-25 03:48
A patch committed to support gdb with python 3.

**Closed** 2017-02-16 06:54 UTC
Labels: bug
