### ISSUE TITLE
Build process does not support cross compilation

### ISSUE THREAD

**Issue by jsakkine-intel** [01org/linux-sgx#36] opened 2016-11-02 08:55 UTC
The build process does not support cross compilation to allow it to be compiled with Yocto or BuildRoot or to be packaged to practically to any distribution because all distributions use some kind of cross compilation environment for compiling the binaries.

The only known working way to compile the distribution is to meet the following requirements:

1. You must compile it in the target machine where you want to run it. 
2. The target machine must have a recent version of Ubuntu installed to it.

I've tried for four weeks to package it for BuildRoot without success. The fixes I've made so far are located in here (*.patch):

http://git.infradead.org/users/jjs/buildroot-isgx.git/tree/HEAD:/package/intel-sgx-psw

Can you put priority on fixing the issue? This practically prevents the whole world from experimenting with SGX because most of the people won't even try it unless they can conveniently install packages from a package repository for their distribution.

**Comment by andyzyb** [comment] 2016-11-04 02:11
Will evaluate the changes to support cross-compiling and get back to you.

**Comment by jsakkine-intel** [comment] 2016-11-14 16:51
Why this was turned as an enhancement? It is clearly a bug.

**Comment by andyzyb** [comment] 2016-11-15 01:51
Current SGX SW release only supports building and executing on Ubuntu 14.04.  Any new OS/environment support is considered as feature request/enhancement.

**Comment by jsakkine-intel** [comment] 2016-11-15 03:04
That's actually a false claim. It only can be said to be support Ubuntu if it can be packaged for Ubuntu, which you cannot do right now because the compilation is broken.

**Comment by jsakkine-intel** [comment] 2016-11-17 22:44
I'll fork this and do a pull request at least the fixes that I've managed to do. It's at least a small step to the right direction.

**Comment by jsakkine-intel** [comment] 2016-11-18 20:24
I'll continue doing small fixes until the stack builds with BuildRoot. Until then can be keep this bug open?

**Comment by jsakkine-intel** [comment] 2016-11-18 20:36
Lets keep this as an enhancement even though the requirements to be able to build this are, well, quite rigid I would say :)

**Comment by andyzyb** [comment] 2017-02-16 06:55
@jsakkine-intel  can we close this?

**Closed** 2017-02-16 07:06 UTC
Labels: enhancement

**Comment by GabrielSVinha** [comment] 2018-01-15 19:12
Is this issue still valid? I've been trying to run the build in a fedora virtual machine hosted by ubuntu and meet the following error:

```
modprobe: ERROR: could not insert 'isgx': Exec format error
```

My guess was that there was an error while cross-compiling, then found this issue. Is this the right place? Can anyone assist me?
@jsakkine-intel @andyzyb

**Comment by lzha101** [comment] 2018-01-16 07:24
Are you trying to install the SGX PSW installer in a fedara virtual machine? Installing PSW in a normal virtual machine is not supported.

**Comment by bodzhang** [comment] 2018-01-16 14:12
Installing the PSW in a VM should work if the virtualization layer properly virtualize the EPC (and other SGX related CPU capability) to the VM.  Experiment patch for SGX virtualization in KVM and Xen available at https://01.org/intel-software-guard-extensions/sgx-virtualization 

To build the SGX PSW or SDK in a VM should not require SGX CPU capabilities in the VM though.

**Comment by GabrielSVinha** [comment] 2018-01-16 17:27
I believe the problem is elsewhere, not even the sgx-driver is being compiled successfully.

**Comment by sergeay** [comment] 2018-01-21 14:03
@Gabriel
1. Seems according to your message above that the compilation was successful but that modprobe failed.
2. Fedora is not supported, (see https://github.com/01org/linux-sgx-driver) but Ubuntu, suse, redhat and centos are.
3. As described above, in order for SGX to work in a VM, you need some patch kvm/qemu/Xen according to the technology you are using.

**Comment by GabrielSVinha** [comment] 2018-01-25 00:58
Thank you @sergeay, @bodzhang and @Izha101. I am using KVM now, are there any plans on supporting fedora?
